---
- name: Creates directory
  file: path=/var/jenkins state=directory

- name: Creates backup directory
  file: path=/var/backups/jenkins state=directory

- name: Copy configs 
  copy: src="{{item}}" dest="/var/jenkins/{{item}}"
  with_items:
    - docker-compose.yml

- name: Install dependencies
  apt: 
    name={{ item }}
    state=present
    update_cache=yes
  with_items: 
    - apt-transport-https
    - ca-certificates
    - apparmor
    - python-dev
    - python-pip
    - postfix

- name: Start postfix
  service:
    name: postfix
    state: started
    
- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pip
    - setuptools
    - docker-compose

- name: Add docker apt repo
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present

- name: Import the Docker repository key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install Docker package
  apt:
    name=docker-engine
    update_cache=yes
    state=latest

- name: Start docker
  service:
    name: docker
    state: started

- shell: "docker network ls | grep proxy-network"
  register: isCreatedNetwork
  ignore_errors: yes

- name: "docker network create"
  command: "docker network create proxy-network"
  when: isCreatedNetwork.stdout == ""


- name: "docker-compose up"
  command: "docker-compose up -d"
  args:
    chdir: /var/jenkins

- pause: seconds=60

- shell: docker run --rm --volume jenkins_jenkins-data:/jenkins_data jenkins cat /jenkins_data/secrets/initialAdminPassword
  register: initialAdminPassword

- debug: msg="initialAdminPassword {{ initialAdminPassword.stdout }}"

- name: Schedule backup
  cron:
    name: "backup"
    minute: "0"
    hour: "0"
    job: "sudo docker run --rm --volume jenkins_jenkins-data:/jenkins_data --volume /var/backups/jenkins:/backup ubuntu tar cvzf /backup/{{lookup('pipe', 'date +%Y-%m-%d-%H%M%S')}}.tar /jenkins_data >> /var/log/jenkins-backup.log 2>&1"